
-- CAMERA
CREATE TABLE camera(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
station_id TEXT NOT NULL, 
show_image INTEGER NOT NULL DEFAULT 0,
resize_image INTEGER NOT NULL,
width INTEGER NOT NULL,
height INTEGER NOT NULL,
fps INTEGER NOT NULL,
data NOT NULL DEFAULT CURRENT_TIMESTAMP);


-- COMMUNICATION
CREATE TABLE communication(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
port TEXT NOT NULL,
baudrate INTEGER NOT NULL,
timeout INTEGER NOT NULL,
preamble INTEGER NOT NULL,
data NOT NULL DEFAULT CURRENT_TIMESTAMP);


-- PROJECT
CREATE TABLE project(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
version TEXT NOT NULL,
data NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- USER
CREATE TABLE user(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
password TEXT NOT NULL,
data NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- WIFI
CREATE TABLE wifi(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
password TEXT NOT NULL,
data NOT NULL DEFAULT CURRENT_TIMESTAMP);
